"""Initial migration

Revision ID: 6b9808c9ed60
Revises: 
Create Date: 2025-03-16 18:33:25.030477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import ForeignKeyConstraint


# revision identifiers, used by Alembic.
revision: str = '6b9808c9ed60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_intervention_requests', schema=None) as batch_op:
        # 外部キー制約を修正（既存の制約を削除して新しい制約を追加）
        batch_op.create_foreign_key(
            "fk_human_intervention_workflow", 
            "workflows", 
            ["workflow_id"], 
            ["id"], 
            ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_intervention_requests', schema=None) as batch_op:
        # 外部キー制約を元に戻す
        batch_op.drop_constraint("fk_human_intervention_workflow", type_='foreignkey')
        batch_op.create_foreign_key(
            "fk_human_intervention_workflow", 
            "workflows", 
            ["workflow_id"], 
            ["id"]
        )
    # ### end Alembic commands ###
