"""Update file management functionality

Revision ID: 3e1d5461c376
Revises: file_table_2025_03_21
Create Date: 2025-03-21 14:54:09.299317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1d5461c376'
down_revision: Union[str, None] = 'file_table_2025_03_21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_regulations')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_created_at')
        batch_op.drop_index('ix_files_file_type')

    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('effective_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('expiration_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expiration_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('effective_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_file_type', ['file_type'], unique=False)
        batch_op.create_index('ix_files_created_at', ['created_at'], unique=False)

    op.create_table('_alembic_tmp_regulations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('structured_content', sa.TEXT(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('effective_date', sa.DATETIME(), nullable=False),
    sa.Column('expiration_date', sa.DATETIME(), nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('keywords', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
