"""update_missing_columns

Revision ID: 90a551cd4506
Revises: dc582fc60db9
Create Date: 2025-03-25 09:05:01.808473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a551cd4506'
down_revision: Union[str, None] = 'dc582fc60db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('workflow_id', sa.String(length=50), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('sample_id', sa.String(length=50), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_responses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('inquiry_id', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('attachment_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_upload_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
        batch_op.alter_column('total_folders',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('processed_folders',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('total_files',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('processed_files',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('failed_files',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_related_id')
        batch_op.drop_index('ix_files_sample_id')

    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
        batch_op.alter_column('sample_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.drop_index('ix_sample_batches_created_at')

    with op.batch_alter_table('sample_results', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
        batch_op.drop_index('ix_sample_results_sample_id')
        batch_op.drop_index('ix_sample_results_workflow_id')

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
        batch_op.alter_column('file_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.drop_index('ix_samples_batch_id')
        batch_op.drop_index('ix_samples_created_at')

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('is_sample_level',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
        batch_op.drop_index('ix_workflows_sample_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index('ix_workflows_sample_id', ['sample_id'], unique=False)
        batch_op.alter_column('is_sample_level',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               nullable=False)

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index('ix_samples_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_samples_batch_id', ['batch_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('file_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               nullable=False)

    with op.batch_alter_table('sample_results', schema=None) as batch_op:
        batch_op.create_index('ix_sample_results_workflow_id', ['workflow_id'], unique=False)
        batch_op.create_index('ix_sample_results_sample_id', ['sample_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               nullable=False)

    with op.batch_alter_table('sample_batches', schema=None) as batch_op:
        batch_op.create_index('ix_sample_batches_created_at', ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('sample_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_sample_id', ['sample_id'], unique=False)
        batch_op.create_index('ix_files_related_id', ['related_id'], unique=False)

    with op.batch_alter_table('batch_upload_jobs', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('failed_files',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
        batch_op.alter_column('processed_files',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
        batch_op.alter_column('total_files',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
        batch_op.alter_column('processed_folders',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
        batch_op.alter_column('total_folders',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               nullable=False)

    op.drop_table('inquiry_responses')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
