"""add_file_size_column

Revision ID: ac59d644c636
Revises: regulation_metadata_field
Create Date: 2025-03-20 15:54:23.588252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac59d644c636'
down_revision: Union[str, None] = 'regulation_metadata_field'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # sample_dataテーブルにfile_sizeカラムを追加
    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        # file_sizeカラムがまだ存在しない場合のみ追加
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # sample_dataテーブルからfile_sizeカラムを削除
    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
